defaults:
  - dataset: mp3d
  - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset}
  - loss: [mse, lpips]

wandb:
  project: pansplat
  name: placeholder
  mode: run

mode: train

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 10
    persistent_workers: true
    batch_size: 4
    seed: 1234
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 4
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 2.e-4
  warm_up_steps: 2000
  cosine_lr: true
  final_div_factor: 1e4
  weight_decay: 0.
  div_factor: 25.
  pct_start: 0.01

checkpointing:
  load: null
  every_n_train_steps: null
  train_time_interval: 10
  pretrained_model: null

train:
  depth_mode: null
  extended_visualization: false
  print_log_every_n_steps: 1

test:
  compute_scores: true
  save_image: true
  save_video: false

val:
  num_visualize: 1

predict:
  extended_visualization: true
  save_image: true

seed: 111123

trainer:
  max_epochs: 10
  max_steps: -1
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  gradient_clip_val: 0.5
  num_sanity_val_steps: 2
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  precision: 32
  deterministic: false
  devices: 1  # or "auto" for all available GPUs

output_dir: null

mvs_only: false
